version: "3.8"
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - vartalap-mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: vartalap

volumes:
  vartalap-mongo:
